# -*- coding: utf-8 -*-
"""2-AnáliseInicial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17BXaMPDMivV9P3x1a5x4cgoUNxoEPNpq
"""

import pandas as pd
import numpy as np

df = pd.read_csv('base2.csv')

df.shape

df.head()

df.dtypes

df.isnull().sum()

"""# N° sem pontuação

.N° sem pontuação é chave primária
"""

df['.N° sem pontuação'].value_counts()

"""# Nº Processo

.Nº Processo também é chave primária. Parece que o atributo anterior é igual a esse sem os pontos.
"""

df['.Nº Processo'].value_counts()

"""# AUTORES

Acredito que a coluna '.AUTORES' são os requerentes, as pessoas que abriram o processo.
"""

df['.AUTORES'].value_counts()

"""# ADVS_AUTORES

A coluna 'ADVS_AUTORES' devem ser os advogados dos requerentes.
"""

df['ADVS_AUTORES'].value_counts()

"""# RÉUS"""

df['RÉUS'].value_counts()

df['RÉUS'].unique()

"""# ADVS_REUS

Advogados dos réus.
"""

df['ADVS_REUS'].value_counts()

"""# Valor da Ação"""

df['Valor Ação'].value_counts()

"""# Classe"""

df['Classe'].value_counts()

"""# Assuntos"""

df['Assuntos'].value_counts()

"""# Tribunal"""

df['.Tribunal'].value_counts()

"""# UF"""

df['.UF'].value_counts()

"""# ÓRGÃO JULGADOR"""

df['ÓRGÃO JULGADOR'].value_counts()

"""# Situação"""

df['.Situação'].value_counts()

"""# Observações"""

df['Observações'].value_counts()

df.columns